---
job: extension
config:
  # this name will be the folder and filename name
  name: "brendan-man001"
  process:
    - type: 'sd_trainer'
      log_dir: "logs"
      log_config:
        log_interval: "50"
      # root folder to save training sessions/samples/weights
      training_folder: "output"
      # uncomment to see performance stats in the terminal every N steps
#      performance_log_every: 1000
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "brendan-man001"
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
        # network_kwargs:
        # only_if_contains:
        #     - "transformer.single_transformer_blocks.7.proj_out"
        #     - "transformer.single_transformer_blocks.12.proj_out"
        #     - "transformer.single_transformer_blocks.16.proj_out"
        #     - "transformer.single_transformer_blocks.20.proj_out"
      save:
        dtype: float16 # precision to save
        save_every: 1000 # save every this many steps
        max_step_saves_to_keep: 4 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
        # You can either set up a HF_TOKEN env variable or you'll be prompted to log-in
#       hf_repo_id: your-username/your-model-slug
#       hf_private: true #whether the repo is private or public
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "F:\\ComfyUI_flus\\dataset\\brendan-charactor-001-single"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 1000  # total number of steps to train 500 - 4000 is a good range3
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw"
        lr: 1e-4
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true  # run 8bit mixed precision
#        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 500 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
#          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"\
          - "Selfie of a [trigger] smiling at the MCG in Melbourne in the stadium. There is a game of AFL playing at the stadium. Professionally shot and color graded. Canon R5 50mm f11"
#          - "a close up photo of bbrendan-man001 smiling at the camera, in a gray studio background. Professionally shot and color graded. Canon R5 50mm f11."
#          - "a photo of brendan-man001 man standing in a studio, modeling a white shirt and blue jeans with white shoes. Professionally shot and color graded. Canon R5 50mm f1.2"
#          - " a full body photo of brendan-man001 man standing in a forest wearing a t-shirt and shorts, with hiking boots on. Professionally shot and color graded. Canon R5 50mm f1.2"
        neg: ""  # not used on flux
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 25
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "brendan-man001"
  version: '1.0'
